version: '3'
 
services:
  db:
    image: postgres:12.3
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456    # 在这里输入你要设置的mysql密码
      POSTGRES_DB: userbehavior
      PGDATA: /var/lib/postgresql/data/pgdata #数据存储文件夹
    networks:
      appnet:
        aliases:
          - pgnet
    ports:
      - "9091:5432"
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data/pgdata

  web1:
    depends_on:
     - db
    image: xz01/django:1.0.1
    container_name: web_django
    working_dir: /home/app
    #ports:
    # - "9092:8000"
    expose:
      - "8000"
    restart: always
    networks:
      appnet:
        aliases:
          - dgnet
    volumes:
      - "./log:/home/app/log"

    command: gunicorn -c ./log/gunicorn.py behaviordata.wsgi
 
  nginx:
    container_name: ng_1
    restart: always
    depends_on:
      - web1
    links:
      - "web1:web"
    #build: ./nginx
    image: nginx:1.19
    ports:
      - 9099:80
    networks:
      appnet:
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
 
networks:
  appnet:
